
services:
  code-server:
    image: codercom/code-server:4.16.0
    container_name: code-server
    user: root
    environment:
      - PASSWORD=Sergio55
    volumes:
      - ./code-server:/home/coder/project
      - ./code-server-config:/root/.config/code-server
      - ./code-server-settings:/root/.local/share/code-server/User
      - ./code-server-extensions:/root/.local/share/code-server/extensions
      - /var/run/docker.sock:/var/run/docker.sock  # Montar el socket de Docker
    ports:
      - "8080:8080"
    restart: always
    entrypoint: ["/bin/sh", "-c", "chmod 666 /var/run/docker.sock && /usr/bin/code-server"]


  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

volumes:
  nginx_data:
  nginx_letsencrypt:
  code-server-config:
  code-server-settings:  # 🔹 Nuevo volumen para temas y configuraciones
  code-server-extensions:  # 🔹 Volumen para extensiones como lo modificarias para que se generara el socket
