services:
  code-server:
    image: codercom/code-server:4.16.0
    container_name: code-server
    user: root
    environment:
      - PASSWORD=Sergio55
    volumes:
      - ./code-server:/home/coder/project
      - ./code-server-config:/root/.config/code-server  # 🔹 Guardar configuración
    ports:
      - "8080:8080"
    restart: always

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "81:81"    # Panel de administración de NPM
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

volumes:
  nginx_data:
  nginx_letsencrypt:
  code-server-config:  # 🔹 Agregar volumen para configuración de code-server
